"""add enums to task

Revision ID: 8492775c13fc
Revises: 132cfbe437e1
Create Date: 2026-04-17 20:48:09.203034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8492775c13fc'
down_revision: Union[str, Sequence[str], None] = '132cfbe437e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('estimated_minutes', sa.Integer(), nullable=True))
    op.alter_column('tasks', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('BACKLOG', 'TODO', 'DOING', 'DONE', name='taskstatus'),
               nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'),
               existing_nullable=False)
    op.drop_column('tasks', 'is_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('BACKLOG', 'TODO', 'DOING', 'DONE', name='taskstatus'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('tasks', 'estimated_minutes')
    # ### end Alembic commands ###
